name: build

on:
  push:
    branches-ignore: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  fleeting-plugin-proxmox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.3'
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: go build -o fleeting-plugin-proxmox ./cmd/fleeting-plugin-proxmox
      - uses: actions/upload-artifact@v4
        with:
          name: upload
          path: fleeting-plugin-proxmox
          retention-days: 1
